version: "3.9"
services:
  maria-db:
    image: "mariadb"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=tirocinio_2022_2023
    volumes:
      - ./dbData:/var/lib/mysql
    restart: unless-stopped
